spring:
  application:
    name: taqwa-ecommerce-app
server:
  port: ${PORT:8900}
---
spring:
  datasource:
    username: ecommerceapp
    password: ecommerceapp
    url: jdbc:mysql://localhost:3306/full-stack-ecommerce
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  data:
    rest:
      base-path: /api
